/**
 * Topics Data Model
 * 
 * Each topic represents one infographic with all its metadata.
 * 
 * Fields:
 * - id: URL slug (e.g., /glyphosate) - should match imageName
 * - brickTitle: One word for homepage mosaic (uppercase)
 * - longTitle: Full title for infographic view and OpenGraph
 * - shareSnippet: Short text for sharing/OpenGraph (under 160 chars)
 * - imageName: Base filename without extension - MUST match files in public/images/
 * - verifyPrompt: Full prompt for AI verification (ChatGPT, Gemini, Grok)
 * 
 * Image files expected for each topic (generated by npm run convert-images):
 * - public/images/{imageName}-thumb.webp
 * - public/images/{imageName}-medium.webp
 * - public/images/{imageName}-large.webp
 * - public/images/{imageName}-original.webp
 */

export interface Topic {
  id: string;
  brickTitle: string;
  longTitle: string;
  shareSnippet: string;
  imageName: string;
  verifyPrompt: string;
}

export const topics: Topic[] = [
  {
    id: 'glyphosate',
    brickTitle: 'GLYPHOSATE',
    longTitle: 'Glyphosate: The Antibiotic in Your Food',
    shareSnippet: 'Glyphosate is a patented antibiotic sprayed on 80% of conventional crops. Here\'s what it does to your gut.',
    imageName: 'glyphosate',
    verifyPrompt: `Verify these claims about glyphosate:
1. Glyphosate is patented as an antibiotic (US Patent 7,771,736)
2. It disrupts the shikimate pathway in gut bacteria
3. It chelates essential minerals (manganese, zinc, iron)
4. WHO IARC classified it as "probable carcinogen" in 2015
5. Found in 80%+ of conventional grain products

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'pufa',
    brickTitle: 'PUFA',
    longTitle: 'PUFA: The Fat That Eats You From Inside',
    shareSnippet: 'Seed oils oxidize in your body and stay in your fat cells for 2 years. Here\'s the chemistry.',
    imageName: 'pufa',
    verifyPrompt: `Verify these claims about polyunsaturated fatty acids (PUFAs):
1. Multiple double bonds in PUFAs oxidize when exposed to heat, light, or oxygen
2. Oxidation creates aldehydes, free radicals, and lipid peroxides
3. PUFAs have a half-life of approximately 2 years in adipose tissue
4. Seed oils contain 50-70% PUFAs vs <5% in animal fats
5. Oxidized PUFAs damage cell membranes and DNA

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'fluoride',
    brickTitle: 'FLUORIDE',
    longTitle: 'Fluoride: More Than a Tooth Thing',
    shareSnippet: 'Fluoride accumulates in your pineal gland and competes with iodine in your thyroid. The research.',
    imageName: 'fluoride',
    verifyPrompt: `Verify these claims about fluoride:
1. Fluoride inhibits over 100 enzymes in the human body
2. Fluoride competes with iodine for thyroid uptake
3. Fluoride accumulates in and calcifies the pineal gland
4. Meta-analyses show 3-7 point IQ reductions in children with high fluoride exposure
5. Skeletal fluorosis occurs with chronic high fluoride intake

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'microplastics',
    brickTitle: 'MICROPLASTICS',
    longTitle: 'Microplastics: They\'re Already Inside You',
    shareSnippet: 'Microplastics have been found in blood, placenta, and brain tissue. Here\'s how they got there.',
    imageName: 'microplastics',
    verifyPrompt: `Verify these claims about microplastics:
1. Microplastics (<5mm) and nanoplastics (<1μm) have been detected in human blood
2. Nanoplastics can cross cell membranes and the blood-brain barrier
3. Microplastics have been found in human placenta and breast milk
4. Bottled water contains significantly more microplastics than tap water
5. Microplastics act as carriers for other environmental toxins

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'salt',
    brickTitle: 'SALT',
    longTitle: 'Refined Salt: Stripped and Adulterated',
    shareSnippet: 'Table salt has 80+ minerals removed and anti-caking agents added. What you\'re actually eating.',
    imageName: 'salt',
    verifyPrompt: `Verify these claims about refined table salt:
1. Table salt is industrially processed to remove 80+ trace minerals
2. Anti-caking agents like sodium aluminosilicate contain aluminum
3. Dextrose (sugar) is added to stabilize added iodine
4. Unrefined salts like Himalayan/Celtic contain 84 trace minerals
5. The refining process uses bleaching agents

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'atrazine',
    brickTitle: 'ATRAZINE',
    longTitle: 'Atrazine: The Chemical Castrator',
    shareSnippet: 'Atrazine feminizes male frogs at 0.1 ppb. It\'s in your tap water. The Tyrone Hayes research.',
    imageName: 'atrazine',
    verifyPrompt: `Verify these claims about atrazine:
1. Atrazine is one of the most commonly detected pesticides in US drinking water
2. Dr. Tyrone Hayes' research showed atrazine feminizes male frogs at 0.1 ppb
3. Atrazine is an endocrine disruptor that affects testosterone and estrogen
4. The EU banned atrazine in 2004 due to groundwater contamination
5. Atrazine exposure is linked to reproductive abnormalities in wildlife

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'bpa',
    brickTitle: 'BPA',
    longTitle: 'BPA: The Synthetic Estrogen Everywhere',
    shareSnippet: 'BPA-free often means BPS or BPF—same mechanism, different molecule. The substitution game.',
    imageName: 'bpa',
    verifyPrompt: `Verify these claims about BPA and its alternatives:
1. BPA (Bisphenol-A) is a synthetic estrogen that binds to estrogen receptors
2. BPA-free products often contain BPS or BPF with similar estrogenic activity
3. Thermal receipt paper is a major source of BPA exposure through skin contact
4. BPA leaches faster from plastics when heated
5. BPA has been detected in 90%+ of tested human urine samples

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'pvc',
    brickTitle: 'PVC',
    longTitle: 'PVC: The Poison Plastic',
    shareSnippet: 'PVC requires phthalate plasticizers that leach continuously. That new shower curtain smell is poison.',
    imageName: 'pvc',
    verifyPrompt: `Verify these claims about PVC (polyvinyl chloride):
1. PVC requires phthalate plasticizers to become flexible
2. Phthalates leach continuously from PVC, especially with heat exposure
3. Phthalates are endocrine disruptors linked to reproductive issues
4. PVC is used in pipes, food packaging, vinyl flooring, and medical tubing
5. The "new shower curtain smell" is off-gassing phthalates and VOCs

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'mercury',
    brickTitle: 'MERCURY',
    longTitle: 'Mercury: The Accumulating Neurotoxin',
    shareSnippet: 'Mercury is lipophilic and crosses the blood-brain barrier. Where it\'s hiding in your life.',
    imageName: 'mercury',
    verifyPrompt: `Verify these claims about mercury exposure:
1. Mercury is lipophilic and accumulates in fatty tissues including the brain
2. Methylmercury crosses the blood-brain barrier
3. Large predatory fish (tuna, swordfish) bioaccumulate mercury
4. Dental amalgam fillings are approximately 50% mercury
5. There is no known safe level of mercury exposure for neurodevelopment

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'fragrances',
    brickTitle: 'FRAGRANCES',
    longTitle: 'Synthetic Fragrances: 300 Chemicals Called "Fragrance"',
    shareSnippet: '"Fragrance" on a label can mean 50-300 undisclosed chemicals. What you\'re actually inhaling.',
    imageName: 'fragrances',
    verifyPrompt: `Verify these claims about synthetic fragrances:
1. "Fragrance" on labels can represent 50-300 undisclosed chemicals
2. Fragrance formulations are protected as trade secrets
3. Phthalates are commonly used as fragrance fixatives
4. Many fragrance chemicals are volatile organic compounds (VOCs)
5. Some fragrance ingredients are known or suspected carcinogens

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'fabric',
    brickTitle: 'FABRIC',
    longTitle: 'Fabric: What\'s Touching Your Skin 24/7',
    shareSnippet: 'Your clothes are treated with formaldehyde, flame retardants, and plastic coatings. The textile industry.',
    imageName: 'fabric',
    verifyPrompt: `Verify these claims about textile treatments:
1. Formaldehyde resins are used in "wrinkle-free" and "permanent press" fabrics
2. Flame retardants in fabrics can be absorbed through skin contact
3. Synthetic fabrics (polyester, nylon) shed microplastic fibers
4. Many fabric dyes contain heavy metals and azo compounds
5. "Moisture-wicking" treatments often use PFAS chemicals

Please cite peer-reviewed sources for each claim.`
  },
  {
    id: 'cookware',
    brickTitle: 'COOKWARE',
    longTitle: 'Cookware: What Leaches Into Your Food',
    shareSnippet: 'Non-stick coatings, aluminum, and heated plastics all transfer into your food. Safe alternatives.',
    imageName: 'cookware',
    verifyPrompt: `Verify these claims about cookware safety:
1. PTFE (Teflon) non-stick coatings release toxic fumes when overheated (>500°F)
2. PFOA used in non-stick manufacturing is a persistent environmental pollutant
3. Aluminum cookware can leach aluminum into acidic foods
4. Scratched non-stick coatings release particles into food
5. Cast iron and stainless steel are the most inert cooking surfaces

Please cite peer-reviewed sources for each claim.`
  },
];

// Helper to get topic by ID
export function getTopicById(id: string): Topic | undefined {
  return topics.find(t => t.id === id);
}

// Helper to get next topic (for "Next" button)
export function getNextTopic(currentId: string): Topic {
  const currentIndex = topics.findIndex(t => t.id === currentId);
  return topics[(currentIndex + 1) % topics.length];
}
