/**
 * Topics Data Model
 *
 * Each topic represents one infographic with all its metadata.
 *
 * Fields:
 * - id: URL slug (e.g., /glyphosate) - should match imageName
 * - brickTitle: One word for homepage mosaic (uppercase)
 * - longTitle: Full title for infographic view and OpenGraph
 * - shareSnippet: Short text for sharing/OpenGraph (under 160 chars)
 * - imageName: Base filename without extension - MUST match files in public/images/
 * - verifyPrompt: Full prompt for AI verification (ChatGPT, Gemini, Grok)
 * - tags: Flexible array for special rendering/behavior (e.g., ["start-here"], ["secret"], ["featured"])
 * - icon: Optional Lucide icon name for the brick
 *
 * Image files expected for each topic (generated by npm run convert-images):
 * - public/images/{imageName}-thumb.webp
 * - public/images/{imageName}-medium.webp
 * - public/images/{imageName}-large.webp
 * - public/images/{imageName}-original.webp
 */

export interface Topic {
  id: string;
  brickTitle: string;
  longTitle: string;
  shareSnippet: string;
  imageName?: string; // Optional - virtual anchors use host's image
  verifyPrompt: string;
  tags: string[];
  icon?: string;
  section?: string; // Optional section grouping for left rail
  groupHost?: string; // If set, this topic renders on the groupHost's page with anchor
  groupOrder?: number; // Order within the group (1, 2, 3...) - host is always first
  scrollOffset?: number; // 0-1 percentage offset within host's image (for virtual anchors)
}

export const topics: Topic[] = [
  {
    id: 'glycation',
    brickTitle: 'GLYCATION',
    longTitle: 'Glycation: Caramelizing From the Inside',
    shareSnippet: 'High blood sugar spikes literally caramelize your arteries and tissues. The biochemistry of sugar damage.',
    imageName: 'glycation',
    verifyPrompt: `Verify these claims about glycation and blood sugar damage:
1. High blood sugar concentration causes glycation (non-enzymatic bonding of sugars to proteins/fats)
2. Glycation creates Advanced Glycation End Products (AGEs) that damage arteries and tissues
3. The process is similar to caramelization - sugars bonding to proteins under heat/concentration
4. AGEs accumulate in arterial walls, kidneys, eyes, and nervous system
5. Glycation is irreversible and contributes to aging and chronic disease

Be honest and reason from first principles. Would concentrated sugar exposure harm tissue structure? What would be the biochemical effects on proteins and fats?`,
    tags: ['start-here'],
    icon: 'Flame',
    section: 'Health Basics'
  },
  {
    id: 'antinutrients',
    brickTitle: 'ANTINUTRIENTS',
    longTitle: 'Plant Antinutrients: Nature\'s Chemical Defense',
    shareSnippet: 'Alkaloids, lectins, oxalates, phytic acid, goitrogens, and phytoestrogens. Why plants don\'t want to be eaten.',
    imageName: 'plant_antinutrient_master',
    verifyPrompt: `Verify these claims about plant antinutrients:
1. Alkaloids (nightshades) damage the nervous system and gut lining
2. Lectins bind to gut cells causing inflammation and leaky gut
3. Oxalates bind minerals and form crystals in kidneys and joints
4. Phytic acid prevents absorption of iron, zinc, and calcium
5. Goitrogens interfere with thyroid iodine uptake
6. Phytoestrogens mimic estrogen and disrupt hormones
7. Glyphosate residue amplifies antinutrient damage
8. Nightshades (tomatoes, potatoes, peppers, eggplants) have double mechanism: lectin gut damage + alkaloid nervous system damage

Elimination priority: nightshades, legumes (lectins), grains (phytic acid), cruciferous vegetables (goitrogens), soy (phytoestrogens + glyphosate).

Be honest and reason from first principles. Would plants evolve chemical defenses against being eaten? What would these compounds do to human digestion and nutrient absorption? Absence of evidence is not evidence of absence.`,
    tags: [],
    icon: 'ShieldAlert',
    section: 'Health Basics'
  },
  // Antinutrient virtual anchors (9 slides total, each ~11.1%)
  {
    id: 'alkaloids',
    brickTitle: 'ALKALOIDS',
    longTitle: 'Alkaloids: Nightshade Neurotoxins',
    shareSnippet: 'Alkaloids from nightshades damage the nervous system and gut lining.',
    verifyPrompt: 'Verify claims about alkaloids in nightshade plants and their effects on the nervous system and gut.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 1,
    scrollOffset: 0.111,
  },
  {
    id: 'lectins',
    brickTitle: 'LECTINS',
    longTitle: 'Lectins: Gut Barrier Disruptors',
    shareSnippet: 'Lectins bind to gut cells causing inflammation and leaky gut.',
    verifyPrompt: 'Verify claims about lectins binding to gut cells and causing inflammation.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 2,
    scrollOffset: 0.222,
  },
  {
    id: 'oxalates',
    brickTitle: 'OXALATES',
    longTitle: 'Oxalates: Crystal Forming Compounds',
    shareSnippet: 'Oxalates bind minerals and form crystals in kidneys and joints.',
    verifyPrompt: 'Verify claims about oxalates binding minerals and forming kidney stones.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 3,
    scrollOffset: 0.333,
  },
  {
    id: 'phytic-acid',
    brickTitle: 'PHYTIC ACID',
    longTitle: 'Phytic Acid: The Mineral Blocker',
    shareSnippet: 'Phytic acid prevents absorption of iron, zinc, and calcium.',
    verifyPrompt: 'Verify claims about phytic acid blocking mineral absorption.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 4,
    scrollOffset: 0.444,
  },
  {
    id: 'goitrogens',
    brickTitle: 'GOITROGENS',
    longTitle: 'Goitrogens: Thyroid Disruptors',
    shareSnippet: 'Goitrogens interfere with thyroid iodine uptake.',
    verifyPrompt: 'Verify claims about goitrogens interfering with thyroid function.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 5,
    scrollOffset: 0.556,
  },
  {
    id: 'phytoestrogens',
    brickTitle: 'PHYTOESTROGENS',
    longTitle: 'Phytoestrogens: Hormone Mimics',
    shareSnippet: 'Phytoestrogens mimic estrogen and disrupt hormones.',
    verifyPrompt: 'Verify claims about phytoestrogens mimicking estrogen.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 6,
    scrollOffset: 0.667,
  },
  {
    id: 'nightshades',
    brickTitle: 'NIGHTSHADES',
    longTitle: 'Nightshades: Double Mechanism Damage',
    shareSnippet: 'Nightshades have double mechanism: lectin gut damage + alkaloid nervous system damage.',
    verifyPrompt: 'Verify claims about nightshades having both lectin and alkaloid damage mechanisms.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 7,
    scrollOffset: 0.778,
  },
  {
    id: 'elimination-priority',
    brickTitle: 'ELIMINATION',
    longTitle: 'Antinutrient Elimination Priority',
    shareSnippet: 'Elimination priority: nightshades, legumes, grains, cruciferous vegetables, soy.',
    verifyPrompt: 'Verify the recommended elimination priority for antinutrient-containing foods.',
    tags: [],
    section: 'Health Basics',
    groupHost: 'antinutrients',
    groupOrder: 8,
    scrollOffset: 0.889,
  },
  {
    id: 'glyphosate',
    brickTitle: 'GLYPHOSATE',
    longTitle: 'Glyphosate: The Antibiotic in Everything',
    shareSnippet: 'Glyphosate is sprayed on GMO crops and as a desiccant before harvest. It\'s an antibiotic destroying your gut microbiota.',
    imageName: 'glyposate_master',
    verifyPrompt: `Verify these claims about glyphosate:
1. "Grass fed" doesn't mean 100% grass fed - animals are often fed GMO corn and soy
2. GMO corn and soy are engineered to survive glyphosate spraying
3. Glyphosate is patented as an antibiotic (US Patent 7,771,736)
4. Glyphosate is sprayed as a desiccant to dry crops before harvest (not for pest control)
5. This desiccant use means direct contamination of grains, lentils, chickpeas, beans, soy, potatoes, buckwheat
6. Glyphosate destroys gut microbiota and leads to autoimmune diseases
7. The EU has banned glyphosate
8. Glyphosate leaches into mushroom substrates when mushrooms are grown on non-organic soy
9. Through contaminated feed (corn/soy), glyphosate accumulates in pig, chicken, farmed fish, and cow tissues
10. When we eat these animals, glyphosate transfers into our tissues

Be honest and reason from first principles. Would an antibiotic sprayed directly on food damage gut bacteria? What would happen to animals fed glyphosate-contaminated feed? Absence of long-term human studies is not evidence of safety.`,
    tags: [],
    icon: 'Sprout',
    section: 'Food Contamination'
  },
  // Glyphosate virtual anchors
  {
    id: 'desiccation',
    brickTitle: 'DESICCATION',
    longTitle: 'Desiccation: Pre-Harvest Spraying',
    shareSnippet: 'Glyphosate is sprayed directly on crops before harvest to dry them out.',
    verifyPrompt: 'Verify claims about glyphosate being used as a desiccant to dry crops before harvest.',
    tags: [],
    section: 'Food Contamination',
    groupHost: 'glyphosate',
    groupOrder: 1,
    scrollOffset: 0.4082,
  },
  {
    id: 'mushrooms',
    brickTitle: 'MUSHROOMS',
    longTitle: 'Mushrooms: Glyphosate in Substrates',
    shareSnippet: 'Glyphosate leaches into mushroom substrates when grown on non-organic soy.',
    verifyPrompt: 'Verify claims about glyphosate contaminating mushrooms grown on non-organic substrates.',
    tags: [],
    section: 'Food Contamination',
    groupHost: 'glyphosate',
    groupOrder: 2,
    scrollOffset: 0.8165,
  },
  {
    id: 'atrazine',
    brickTitle: 'ATRAZINE',
    longTitle: 'Atrazine: Chemical Feminization in Your Water',
    shareSnippet: 'Atrazine disrupts the aromatase pathway and feminizes males. It\'s in your groundwater, skin absorption, and breathing.',
    imageName: 'atrazine',
    verifyPrompt: `Verify these claims about atrazine:
1. Atrazine disrupts the aromatase pathway that converts testosterone to estrogen
2. The famous frog study showed atrazine feminizes male frogs at extremely low concentrations
3. Atrazine has been banned in the EU for 20+ years
4. Atrazine enters groundwater and remains without reverse osmosis filtration
5. Exposure occurs through drinking tap water, bathing (skin absorption), and breathing
6. Atrazine particularly affects children and developing organisms
7. It disrupts sexual development and hormone balance in humans

Be honest and reason from first principles. If a chemical feminizes frogs at trace levels, would it affect human hormones? What would happen to children exposed during development? Absence of evidence is not evidence of absence.`,
    tags: [],
    icon: 'Droplets',
    section: 'Water Contamination'
  },
  {
    id: 'reverse-osmosis',
    brickTitle: 'REVERSE OSMOSIS',
    longTitle: 'Why You Need Reverse Osmosis Filtration',
    shareSnippet: 'Atrazine, PFAS, fluoride, pharmaceuticals, and heavy metals. What\'s actually in your tap water.',
    imageName: 'tap_water',
    verifyPrompt: `Verify these claims about water contaminants and reverse osmosis:
1. Municipal water contains atrazine from agricultural runoff
2. PFAS (forever chemicals) persist in water supplies
3. Fluoride added to water is industrial waste, not pharmaceutical-grade dental fluoride
4. Fluoride accumulates in bones and tissues permanently
5. Birth control hormones and pharmaceuticals pass through wastewater treatment and return to tap water
6. Heavy metals (lead, arsenic, mercury) contaminate many water systems
7. Standard filtration doesn't remove these contaminants
8. Reverse osmosis removes: atrazine, PFAS, fluoride, pharmaceuticals, and heavy metals

Be honest and reason from first principles. Would industrial waste added to drinking water accumulate in the body? Can wastewater treatment remove all pharmaceutical compounds? What happens when you bathe in contaminated water?`,
    tags: [],
    icon: 'Filter',
    section: 'Water Contamination'
  },
  {
    id: 'salt-scam',
    brickTitle: 'PINK/SEA SALT',
    longTitle: 'The Mineral Salt Scam: Lead, Arsenic, and Microplastics',
    shareSnippet: 'Celtic sea salt has lead and arsenic. Himalayan salt is mined in Pakistan. Sea salt concentrates ocean pollution.',
    imageName: 'mineral_salt_bullshit',
    verifyPrompt: `Verify these claims about "healthy" salts:
1. Independent lab tests show Celtic sea salt contains measurable lead and arsenic
2. Pink Himalayan salt is mined in Pakistan with minimal quality oversight
3. Sea salt production concentrates whatever is floating in the ocean: oil particles, heavy metals, microplastics
4. "Mineral content" in fancy salts is used as a marketing feature to hide contamination
5. Ocean pollution (plastic, chemicals, metals) directly concentrates into sea salt
6. The "84 minerals" claim is unregulated and includes toxins

Cite independent laboratory testing results for Celtic sea salt contamination.

Be honest and reason from first principles. If the ocean contains pollution, would evaporated sea water concentrate those pollutants? Is "mined in Pakistan" a guarantee of purity for American consumers?`,
    tags: [],
    icon: 'Sparkles',
    section: 'Food Contamination'
  },
  {
    id: 'wood-bamboo',
    brickTitle: 'WOOD/BAMBOO',
    longTitle: 'Wood and Bamboo: Fumigation and Formaldehyde',
    shareSnippet: 'ISTM-15 law requires fumigation of all imported wood. Rattan, wicker, and bamboo are heavily treated.',
    imageName: 'wood_problem',
    verifyPrompt: `Verify these claims about wood and bamboo products:
1. ISTM-15 is a US law requiring all wood imports (except Canadian) to be fumigated
2. Methyl bromide fumigation is the standard treatment method
3. Rattan and wicker furniture undergoes double fumigation: sulfur dioxide + methyl bromide
4. Bamboo products are fumigated and chemically treated
5. "Food grade" cutting boards often use MDF or PDF with formaldehyde-containing adhesives
6. These materials continuously off-gas formaldehyde into homes
7. Formaldehyde is a known carcinogen

Be honest and reason from first principles. Would fumigation chemicals remain in porous wood fibers? What happens when these materials are used daily in your home or for food preparation?`,
    tags: [],
    icon: 'Trees',
    section: 'Materials'
  },
  // Wood/Bamboo virtual anchors
  {
    id: 'wood-glue',
    brickTitle: 'WOOD GLUE',
    longTitle: 'Wood Glue: Formaldehyde Adhesives',
    shareSnippet: 'MDF and plywood use formaldehyde-containing adhesives that continuously off-gas.',
    verifyPrompt: 'Verify claims about formaldehyde in wood adhesives and off-gassing from composite wood products.',
    tags: [],
    section: 'Materials',
    groupHost: 'wood-bamboo',
    groupOrder: 1,
    scrollOffset: 0.3333,
  },
  {
    id: 'wood-finish',
    brickTitle: 'WOOD FINISH',
    longTitle: 'Wood Finish: Toxic Coatings',
    shareSnippet: 'Wood finishes and stains contain VOCs and toxic chemicals.',
    verifyPrompt: 'Verify claims about toxic chemicals in wood finishes and stains.',
    tags: [],
    section: 'Materials',
    groupHost: 'wood-bamboo',
    groupOrder: 2,
    scrollOffset: 0.6666,
  },
  {
    id: 'clean-storage',
    brickTitle: 'CLEAN STORAGE',
    longTitle: 'Clean Storage: What\'s Actually Safe',
    shareSnippet: 'Mason jars have plastic linings. Only glass, stainless steel, and cast iron are truly safe. Weck jars use natural rubber.',
    imageName: 'clean_storage',
    verifyPrompt: `Verify these claims about food storage safety:
1. Mason jar lids have plastic/polymer lining on the inside that contacts food
2. Plastic containers leach chemicals into food, especially with heat or acidic foods
3. Wooden containers harbor bacteria and can leach tannins/resins
4. Cardboard packaging leaches chemicals and breaks down into food
5. Safe storage materials: glass, stainless steel, cast iron, glass enamel coating
6. Weck jars use natural rubber gaskets (not synthetic rubber) which don't leach
7. Synthetic rubber gaskets contain plasticizers and vulcanizing agents that can migrate into food

Be honest and reason from first principles. Would plastic components in contact with food remain inert over time? What happens when acidic or fatty foods touch polymer linings? Is there truly such a thing as "food-safe" plastic?`,
    tags: [],
    icon: 'Package',
    section: 'Materials'
  },
];

// Helper to get topic by ID
export function getTopicById(id: string): Topic | undefined {
  return topics.find(t => t.id === id);
}

// Check if a topic is a group host (other topics reference it via groupHost)
export function isGroupHost(topicId: string): boolean {
  return topics.some(t => t.groupHost === topicId);
}

// Get all topics that belong to a group (including the host), in order
export function getGroupedTopics(hostId: string): Topic[] {
  const host = topics.find(t => t.id === hostId);
  if (!host) return [];

  const members = topics
    .filter(t => t.groupHost === hostId)
    .sort((a, b) => (a.groupOrder ?? 0) - (b.groupOrder ?? 0));

  return [host, ...members];
}

// Get the proper URL for a topic (with anchor if it's grouped)
export function getTopicUrl(topic: Topic): string {
  if (topic.groupHost) {
    return `/${topic.groupHost}#${topic.id}`;
  }
  return `/${topic.id}`;
}

// Get the host topic for a grouped topic (or itself if standalone/host)
export function getHostTopic(topic: Topic): Topic {
  if (topic.groupHost) {
    return topics.find(t => t.id === topic.groupHost) ?? topic;
  }
  return topic;
}

// Helper to get next topic (for "Next" button)
// Always goes to the next main topic (skips grouped sub-topics)
export function getNextTopic(currentId: string): Topic {
  const current = getTopicById(currentId);
  if (!current) {
    return topics[0];
  }

  // If current is a grouped topic, use its host as the starting point
  const startId = current.groupHost ?? current.id;
  const startIndex = topics.findIndex(t => t.id === startId);

  // Find the next topic that is NOT a grouped sub-topic
  for (let i = 1; i < topics.length; i++) {
    const nextIndex = (startIndex + i) % topics.length;
    const nextTopic = topics[nextIndex];
    // Skip grouped topics - only return standalone topics or group hosts
    if (!nextTopic.groupHost) {
      return nextTopic;
    }
  }

  return topics[0];
}
