/**
 * Topics Data Model
 *
 * Each topic represents one infographic with all its metadata.
 *
 * Fields:
 * - id: URL slug (e.g., /glyphosate) - should match imageName
 * - brickTitle: One word for homepage mosaic (uppercase)
 * - longTitle: Full title for infographic view and OpenGraph
 * - shareSnippet: Short text for sharing/OpenGraph (under 160 chars)
 * - imageName: Base filename without extension - MUST match files in public/images/
 * - verifyPrompt: Full prompt for AI verification (ChatGPT, Gemini, Grok)
 * - tags: Flexible array for special rendering/behavior (e.g., ["start-here"], ["secret"], ["featured"])
 * - icon: Optional Lucide icon name for the brick
 *
 * Image files expected for each topic (generated by npm run convert-images):
 * - public/images/{imageName}-thumb.webp
 * - public/images/{imageName}-medium.webp
 * - public/images/{imageName}-large.webp
 * - public/images/{imageName}-original.webp
 */

export interface Topic {
  id: string;
  brickTitle: string;
  longTitle: string;
  shareSnippet: string;
  imageName: string;
  verifyPrompt: string;
  tags: string[];
  icon?: string;
}

export const topics: Topic[] = [
  {
    id: 'glycation',
    brickTitle: 'GLYCATION',
    longTitle: 'Glycation: Caramelizing From the Inside',
    shareSnippet: 'High blood sugar spikes literally caramelize your arteries and tissues. The biochemistry of sugar damage.',
    imageName: 'glycation',
    verifyPrompt: `Verify these claims about glycation and blood sugar damage:
1. High blood sugar concentration causes glycation (non-enzymatic bonding of sugars to proteins/fats)
2. Glycation creates Advanced Glycation End Products (AGEs) that damage arteries and tissues
3. The process is similar to caramelization - sugars bonding to proteins under heat/concentration
4. AGEs accumulate in arterial walls, kidneys, eyes, and nervous system
5. Glycation is irreversible and contributes to aging and chronic disease

Be honest and reason from first principles. Would concentrated sugar exposure harm tissue structure? What would be the biochemical effects on proteins and fats?`,
    tags: ['start-here'],
    icon: 'Flame'
  },
  {
    id: 'antinutrients',
    brickTitle: 'ANTINUTRIENTS',
    longTitle: 'Plant Antinutrients: Nature\'s Chemical Defense',
    shareSnippet: 'Alkaloids, lectins, oxalates, phytic acid, goitrogens, and phytoestrogens. Why plants don\'t want to be eaten.',
    imageName: 'plant_antinutrient_master',
    verifyPrompt: `Verify these claims about plant antinutrients:
1. Alkaloids (nightshades) damage the nervous system and gut lining
2. Lectins bind to gut cells causing inflammation and leaky gut
3. Oxalates bind minerals and form crystals in kidneys and joints
4. Phytic acid prevents absorption of iron, zinc, and calcium
5. Goitrogens interfere with thyroid iodine uptake
6. Phytoestrogens mimic estrogen and disrupt hormones
7. Glyphosate residue amplifies antinutrient damage
8. Nightshades (tomatoes, potatoes, peppers, eggplants) have double mechanism: lectin gut damage + alkaloid nervous system damage

Elimination priority: nightshades, legumes (lectins), grains (phytic acid), cruciferous vegetables (goitrogens), soy (phytoestrogens + glyphosate).

Be honest and reason from first principles. Would plants evolve chemical defenses against being eaten? What would these compounds do to human digestion and nutrient absorption? Absence of evidence is not evidence of absence.`,
    tags: [],
    icon: 'ShieldAlert'
  },
  {
    id: 'glyphosate',
    brickTitle: 'GLYPHOSATE',
    longTitle: 'Glyphosate: The Antibiotic in Everything',
    shareSnippet: 'Glyphosate is sprayed on GMO crops and as a desiccant before harvest. It\'s an antibiotic destroying your gut microbiota.',
    imageName: 'glyposate_master',
    verifyPrompt: `Verify these claims about glyphosate:
1. "Grass fed" doesn't mean 100% grass fed - animals are often fed GMO corn and soy
2. GMO corn and soy are engineered to survive glyphosate spraying
3. Glyphosate is patented as an antibiotic (US Patent 7,771,736)
4. Glyphosate is sprayed as a desiccant to dry crops before harvest (not for pest control)
5. This desiccant use means direct contamination of grains, lentils, chickpeas, beans, soy, potatoes, buckwheat
6. Glyphosate destroys gut microbiota and leads to autoimmune diseases
7. The EU has banned glyphosate
8. Glyphosate leaches into mushroom substrates when mushrooms are grown on non-organic soy
9. Through contaminated feed (corn/soy), glyphosate accumulates in pig, chicken, farmed fish, and cow tissues
10. When we eat these animals, glyphosate transfers into our tissues

Be honest and reason from first principles. Would an antibiotic sprayed directly on food damage gut bacteria? What would happen to animals fed glyphosate-contaminated feed? Absence of long-term human studies is not evidence of safety.`,
    tags: [],
    icon: 'Sprout'
  },
  {
    id: 'atrazine',
    brickTitle: 'ATRAZINE',
    longTitle: 'Atrazine: Chemical Feminization in Your Water',
    shareSnippet: 'Atrazine disrupts the aromatase pathway and feminizes males. It\'s in your groundwater, skin absorption, and breathing.',
    imageName: 'atrazine',
    verifyPrompt: `Verify these claims about atrazine:
1. Atrazine disrupts the aromatase pathway that converts testosterone to estrogen
2. The famous frog study showed atrazine feminizes male frogs at extremely low concentrations
3. Atrazine has been banned in the EU for 20+ years
4. Atrazine enters groundwater and remains without reverse osmosis filtration
5. Exposure occurs through drinking tap water, bathing (skin absorption), and breathing
6. Atrazine particularly affects children and developing organisms
7. It disrupts sexual development and hormone balance in humans

Be honest and reason from first principles. If a chemical feminizes frogs at trace levels, would it affect human hormones? What would happen to children exposed during development? Absence of evidence is not evidence of absence.`,
    tags: [],
    icon: 'Droplets'
  },
  {
    id: 'reverse-osmosis',
    brickTitle: 'REVERSE OSMOSIS',
    longTitle: 'Why You Need Reverse Osmosis Filtration',
    shareSnippet: 'Atrazine, PFAS, fluoride, pharmaceuticals, and heavy metals. What\'s actually in your tap water.',
    imageName: 'tap_water',
    verifyPrompt: `Verify these claims about water contaminants and reverse osmosis:
1. Municipal water contains atrazine from agricultural runoff
2. PFAS (forever chemicals) persist in water supplies
3. Fluoride added to water is industrial waste, not pharmaceutical-grade dental fluoride
4. Fluoride accumulates in bones and tissues permanently
5. Birth control hormones and pharmaceuticals pass through wastewater treatment and return to tap water
6. Heavy metals (lead, arsenic, mercury) contaminate many water systems
7. Standard filtration doesn't remove these contaminants
8. Reverse osmosis removes: atrazine, PFAS, fluoride, pharmaceuticals, and heavy metals

Be honest and reason from first principles. Would industrial waste added to drinking water accumulate in the body? Can wastewater treatment remove all pharmaceutical compounds? What happens when you bathe in contaminated water?`,
    tags: [],
    icon: 'Filter'
  },
  {
    id: 'salt-scam',
    brickTitle: 'SALT SCAM',
    longTitle: 'The Mineral Salt Scam: Lead, Arsenic, and Microplastics',
    shareSnippet: 'Celtic sea salt has lead and arsenic. Himalayan salt is mined in Pakistan. Sea salt concentrates ocean pollution.',
    imageName: 'mineral_salt_bullshit',
    verifyPrompt: `Verify these claims about "healthy" salts:
1. Independent lab tests show Celtic sea salt contains measurable lead and arsenic
2. Pink Himalayan salt is mined in Pakistan with minimal quality oversight
3. Sea salt production concentrates whatever is floating in the ocean: oil particles, heavy metals, microplastics
4. "Mineral content" in fancy salts is used as a marketing feature to hide contamination
5. Ocean pollution (plastic, chemicals, metals) directly concentrates into sea salt
6. The "84 minerals" claim is unregulated and includes toxins

Cite independent laboratory testing results for Celtic sea salt contamination.

Be honest and reason from first principles. If the ocean contains pollution, would evaporated sea water concentrate those pollutants? Is "mined in Pakistan" a guarantee of purity for American consumers?`,
    tags: [],
    icon: 'Sparkles'
  },
  {
    id: 'wood-bamboo',
    brickTitle: 'WOOD/BAMBOO',
    longTitle: 'Wood and Bamboo: Fumigation and Formaldehyde',
    shareSnippet: 'ISTM-15 law requires fumigation of all imported wood. Rattan, wicker, and bamboo are heavily treated.',
    imageName: 'wood_problem',
    verifyPrompt: `Verify these claims about wood and bamboo products:
1. ISTM-15 is a US law requiring all wood imports (except Canadian) to be fumigated
2. Methyl bromide fumigation is the standard treatment method
3. Rattan and wicker furniture undergoes double fumigation: sulfur dioxide + methyl bromide
4. Bamboo products are fumigated and chemically treated
5. "Food grade" cutting boards often use MDF or PDF with formaldehyde-containing adhesives
6. These materials continuously off-gas formaldehyde into homes
7. Formaldehyde is a known carcinogen

Be honest and reason from first principles. Would fumigation chemicals remain in porous wood fibers? What happens when these materials are used daily in your home or for food preparation?`,
    tags: [],
    icon: 'Trees'
  },
  {
    id: 'clean-storage',
    brickTitle: 'CLEAN STORAGE',
    longTitle: 'Clean Storage: What\'s Actually Safe',
    shareSnippet: 'Mason jars have plastic linings. Only glass, stainless steel, and cast iron are truly safe. Weck jars use natural rubber.',
    imageName: 'clean_storage',
    verifyPrompt: `Verify these claims about food storage safety:
1. Mason jar lids have plastic/polymer lining on the inside that contacts food
2. Plastic containers leach chemicals into food, especially with heat or acidic foods
3. Wooden containers harbor bacteria and can leach tannins/resins
4. Cardboard packaging leaches chemicals and breaks down into food
5. Safe storage materials: glass, stainless steel, cast iron, glass enamel coating
6. Weck jars use natural rubber gaskets (not synthetic rubber) which don't leach
7. Synthetic rubber gaskets contain plasticizers and vulcanizing agents that can migrate into food

Be honest and reason from first principles. Would plastic components in contact with food remain inert over time? What happens when acidic or fatty foods touch polymer linings? Is there truly such a thing as "food-safe" plastic?`,
    tags: [],
    icon: 'Package'
  },
];

// Helper to get topic by ID
export function getTopicById(id: string): Topic | undefined {
  return topics.find(t => t.id === id);
}

// Helper to get next topic (for "Next" button)
export function getNextTopic(currentId: string): Topic {
  const currentIndex = topics.findIndex(t => t.id === currentId);
  return topics[(currentIndex + 1) % topics.length];
}
